#+BEGIN_COMMENT
* Some Modelling Problems

For each of the following situations, design an algorithm that produces a formula which is satisfiable if and only if the situation can be resolved.

1. Consider three persons A, B and C who need to be seated in a row. But:
   - A does not want to seat next to C. 
   - A does not want to sit in the left chair.
   - B does not want to sit to the right of C.
2. A problem of covering $m$ subjects with $k$ teachers maybe defined as follows. Let $T: \{T_1, \cdots T_n\}$ be a set of teachers, and $S: \{S_1, \cdots S_m\}$ be a set of subjects. Each teacher \(t \in T\) can teach some subset \(S_t \subseteq S\) of the subjects S. Given a natural number \(k \leq n\), is there a subset of size $k$ of te teachers that together cover all the $m$ subjects?
3. Given a graph, output a propositional formula that is satisfiable if and only if the graph has a hamiltonian cycle
#+END_COMMENT

* Solutions to Tutorial Problems

** Problem 7

**Claim:** The following are equivalent:

1. $\models \alpha$ in the field of sets sense.
2. $\models \alpha$ in the usual sense.

**Proof:**

($1 \implies 2$)

Suppose that $\alpha$ is valid in the field of sets sense. Now, suppose $X$ is some set and $\mathcal{F} = \{\phi, X\}$. Let $v$ be any valuation in $PV \to \{\top, \bot\}$. We construct $u : PV \to \mathcal{F}$, such that $u(p) = X$ if $v(p) = \top$ and $u(w) = \phi$ otherwise, for all $p \in PV$. If we show that $v \models \alpha$ iff $u \models \alpha$, we will be done since we know that $u$ indeed satisfies $\alpha$ (because $\alpha$ is valid in the field of sets sense).

So, we show that $u \models \alpha$ if and only if $v \models \alpha$. The proof is by structure on the induction of $\alpha$.

1. If $\alpha$ is a propositional variable, then the claim holds by construction of $u$.
2. If $\alpha = \varphi \lor \psi$, then $\hat{u}(\alpha) = \hat{u}(\varphi) \cup \hat{u}(\psi)$. Suppose $v \models \varphi \lor \psi$. Then, without loss of generality, say $v \models \varphi$. But by induction hypothesis, this means $u \models \varphi$ and hence $\hat{u}(\varphi) = X = \hat{u}(\varphi) \cup \hat{u}(\psi)$, and thus $u \models \varphi \lor \psi$. The converse direction is also similar.
3. (The proof for $\alpha = \varphi \land \psi$ is similar. Please try this.)
4. If $\alpha = \neg \varphi$, then $v \models \neg \varphi$ if and only if $v \not \models \varphi$ if and only if (by induction hypothesis) $u \not \models \varphi$ if and only if $\hat{u}(\varphi) = \phi$ if and only if $\hat{u}(\neg \varphi) = X$ if and only if $u \models \neg \varphi$.

($2 \implies 1$)

We prove the contrapositive of the statement. Suppose that $\mathcal{F}$ is a field of sets over some set $X$ along with a valuation $u$ such that $u \not \models \alpha$. We will show that there is a valuation $v$ (in the usual sense) such that $v \not \models \alpha$.

By semantics, our assumption means that there is an $x \in X$ such that $x \not \in \hat{u}(\alpha)$. Construct $v: PV \to \{\top, \bot\}$ such that $v(p) = \top$ if $x \in u(p)$ and $v(p) = \bot$ otherwise.

Now, show by induction on the structure of formulae that for any well formed formula $\varphi$, $\hat{v}(\varphi) = \top$ if and only if $x \in \hat{u}(\varphi)$. But this means that $v \not \models \varphi$ because of the choice of $x$. $\blacksquare$
   
